fint:
  application-id: fint-customer-gateway
  org-id: fintlabs.no
server:
  max-http-header-size: 40KB
  error:
    include-message: always
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    include:
      - kafka
      - resource-server